[fr]
  languageName = "French"
  contentDir = "content/fr"
  weight = 10
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-CA"
    footer = ''
    alertText = ''

[en]
  languageName = "English"
  contentDir = "content/en"
  disabled = true
  weight = 15
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = ''
    alertText = ''


