[[main]]
  identifier = "projects"
  name = "Projets"
  url = "#"
  weight = 5

[[main]]
  parent = "projects"
  name = "Alacod"
  url = "https://alacod.bascanada.org"
  weight = 10
  [main.params]
    newtab = true

[[main]]
  parent = "projects"
  name = "Logviewer"
  url = "/fr/logviewer"
  weight = 20

[[main]]
  parent = "projects"
  name = "Allumette"
  url = "/fr/allumette"
  weight = 30

[[main]]
  name = "Gouvernance"
  url = "/fr/gouvernance"
  weight = 10

[[main]]
  name = "Blog"
  url = "/fr/blog/"
  weight = 20


[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/bascanada"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Discord"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"icon icon-tabler icons-tabler-outline icon-tabler-brand-discord\"><path stroke=\"none\" d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M8 12a1 1 0 1 0 2 0a1 1 0 0 0 -2 0\" /><path d=\"M14 12a1 1 0 1 0 2 0a1 1 0 0 0 -2 0\" /><path d=\"M15.5 17c0 1 1.5 3 2 3c1.5 0 2.833 -1.667 3.5 -3c.667 -1.667 .5 -5.833 -1.5 -11.5c-1.457 -1.015 -3 -1.34 -4.5 -1.5l-.972 1.923a11.913 11.913 0 0 0 -4.053 0l-.975 -1.923c-1.5 .16 -3.043 .485 -4.5 1.5c-2 5.667 -2.167 9.833 -1.5 11.5c.667 1.333 2 3 3.5 3c.5 0 2 -2 2 -3\" /><path d=\"M7 16.5c3.5 1 6.5 1 10 0\" /></svg>"
  url = "https://discord.gg/bfs9jxG7aX"
  weight = 20

[[social]]
  name = "YouTube"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"icon icon-tabler icons-tabler-outline icon-tabler-brand-youtube\"><path stroke=\"none\" d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M2 8a4 4 0 0 1 4 -4h12a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-12a4 4 0 0 1 -4 -4v-8z\" /><path d=\"M10 9l5 3l-5 3z\" /></svg>"
  url = "https://youtube.com/@BasCanada"
  weight = 30


[[footer]]
  name = "Politique de confidentialit√©"
  url = "/fr/privacy/"
  weight = 10

[[footer]]
  name = "Code de conduite"
  url = "https://github.com/bascanada/.github/blob/main/CODE_OF_CONDUCT.md" # Lien vers votre repo GitHub
  weight = 20

[[footer]]
  name = "Licence (CC-BY-SA)"
  url = "https://creativecommons.org/licenses/by-sa/4.0/deed.fr"
  weight = 30

[[footer]]
  name = "Nous joindre"
  url = "mailto:bascanada1841@gmail.com"
  weight = 40
